### ISSUE TITLE
Add form-based configuration to (optionally?) replace config.php

### ISSUE THREAD

**Issue by sheshiresat** [sheshiresat/floodgate#1]
Apparently, editing the source code is too complex for some people, and a configuration UI would be an interesting project anyway!

 - Must be secure
 - Must be removable

I think editing the source code is simple, but I&#700;m the one that wrote it, so of course I understand it! 😏

**Comment by somebody2001** [comment]
not working

**Comment by sheshiresat** [comment]
@somebody2001 It's not supposed to work; it does&#700nt exist yet. This issue is sort of like a TODO-list entry.

**Comment by sheshiresat** [comment]
This would be done by now, but I want it to be completely secure over HTTP. I think encrypting everything with a pre-set RSA keypair between the client and server would work, and am working on a sane way to do it. Trust me, I&#700;m not _completely insane_. (Hopefully.)

**Comment by sheshiresat** [comment]
So far, my plan is along these lines:

 0. On setup, the user specifies a secret phrase in a protected, one-line file on the server.

 1. The user requests `http://faucet.example.com/admin.php`
 2. The server reads the secret phrase, and derives an RSA keypair from it in some deterministic fashion (and maybe caches the result?)
 3. The server sends the client an HTML file containing:
    - A text box to enter the secret phrase
    - A "decrypt" button
    - A base64 blob of the actual configuration form, encrypted with the RSA key
    - Lots of javascript \:vomit\:
 4. The user enters the phrase and clicks "decrypt", triggering a local script that generates the same RSA keypair, decodes the form data, and inserts it into the page
 5. The user edits the form as desired, then hits an "encrypt" button that makes a new encrypted blob
 6. The user clicks "submit", sending the encrypted blob to the server
 7. The server decrypts the blob and does stuff

This setup should be immune to man-in-the-middle attacks, even over plain HTTP. If an attacker has access to the server and/or the user&#700;s computer through some other method, then the security of the form won&#700;t matter anyway.

**Comment by sheshiresat** [comment]
Nope.
